name: KhaiBaoThongTin
main: NZS\PIF\KhaiBao
api:
  - 3.2.0
  - 3.0.0
mcbe-protocol:
  - 448
  - 469
  - 465
version: 1.5
author: NZS
website: github.com/NZSigourney/KhaiBao
depends:
  - FormAPI
  - Marry